### PR TITLE
Added more yes and no matches.

### LINKED ISSUE #1: Detect more colloquial variations
yeah, ya, nah, ye, nope, etc

If someone was writing a chat bot, for example, they'd use your library to detect these variations, right? Probably add them under "somewhat yes"

### PR DESCRIPTION
**Pull request by Erk-**
Fixes #1

### CODE REVIEW

**Comment by perryprog** [comment]
@Erk- can you please add some more unit tests? You can never be too safe™

**Comment by kohikudasai** [comment]
@Erk- Please add more unit tests.

**Comment by perryprog** [comment]
@Erk- hurry up please, I have a client that's waiting on a release that depends on this new version

**Comment by kohikudasai** [comment]
20000% coverage!

**Comment by Erk-** [comment]
I am also going to do some fuzzing of the lib to make sure it works.

**Comment by perryprog** [comment]
This should be good now.

**Review by perryprog — APPROVED** [review]

**Comment by kohikudasai** [comment]
Thanks for your contribution!

**Comment by Erk-** [comment]
It was my pleasure to work on it. :)

2018-07-06 17:57 GMT+02:00 president moon <notifications@github.com>:

**Pull request merged**
